#!/bin/bash

# Remove unused empty directories commonly found on new installs
for dir in Downloads Documents Music Pictures Video; do
  [ -d "$HOME/$dir" ] && rmdir -v "$HOME/$dir"
done

# Create custom directories
for dir in tmp p .vim-swap .desktop .templates .public .config; do
  mkdir -pv "$HOME/$dir"
done

# Create symlinks to all dotfiles (in home dir), also add dot to their names
for file in $(find dotfiles/ -type f); do
  if [[ "$file" =~ \.copy$ ]]; then
    filename=${file%\.copy}
    target="$HOME/.${filename#dotfiles/}"
    target_dir=$(dirname "$target")
    [ ! "$file" -nt "$target" ] && continue
    mkdir -pv "$target_dir"
    cp -bv "$file" "$target"
  else
    target="$HOME/.${file#dotfiles/}"
    target_dir=$(dirname "$target")
    target_canon=$(readlink -f "$target")
    file_canon=$(readlink -f "$file")
    [ "$target_canon" = "$file_canon" ] && continue
    mkdir -pv "$target_dir"
    ln -sbv "$file_canon" "$target"
  fi
done
