#!/bin/bash

npm i -g \
  eslint \
  eslint_d \
  eslint-plugin-react \
  eslint-config-airbnb \
  eslint-plugin-jsx-a11y \
  eslint-plugin-import \
  babel-eslint \
  babel-preset-es2015 \
  babel-preset-react \
  coffee-script \
  gulp \
  http-server \
  jsonlint \
  nodemon \
  ramda-cli \
  diff-so-fancy \
  cloc \
  npm-check

sudo apt-get install git
sudo apt-get install gitk
sudo apt-get install git-extras
sudo apt-get install silversearcher-ag
sudo apt-get install meld
sudo apt-get install baobab

# For compiling YouCompleteMe
sudo apt-get install build-essential cmake python-dev python3-dev

sudo pip install pygments # For ranger syntax highlighting
sudo pip3 install neovim-remote
