#!/bin/bash

npm i -g npm
npm i -g babel
npm i -g eslint
npm i -g babel-eslint
npm i -g eslint-plugin-react
npm i -g gulp
npm i -g http-server
npm i -g jsonlint
npm i -g nodemon

sudo apt-get install git-extras
