[tool.poetry]
name = "dev"
version = "0.1.0"
description = ""
authors = ["David Moody <david@davidxmoody.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pynvim = "^0.5.0"
jupyter-client = "^8.6.1"
