#!/bin/bash

# INSTALL HELPERS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

install_fedora() {
  hash dnf 2>/dev/null && \
    sudo dnf -yq install "$@"
}

install_ubuntu() {
  hash apt-get 2>/dev/null && \
    sudo apt-get -yq install "$@"
}

install() {
  if hash dnf 2>/dev/null; then
    install_fedora "$@"
  else
    install_ubuntu "$@"
  fi
}

# SETUP DIRS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

for dir in Downloads Documents Music Pictures Video; do
  [ -d "$HOME/$dir" ] && rmdir -v "$HOME/$dir"
done

for dir in tmp p .vim-swap .desktop .templates .public .config; do
  mkdir -pv "$HOME/$dir"
done

for file in $(find dotfiles/ -type f); do
  if [[ "$file" =~ \.copy$ ]]; then
    filename=${file%\.copy}
    target="$HOME/.${filename#dotfiles/}"
    target_dir=$(dirname "$target")
    [ ! "$file" -nt "$target" ] && continue
    mkdir -pv "$target_dir"
    cp -bv "$file" "$target"
  else
    target="$HOME/.${file#dotfiles/}"
    target_dir=$(dirname "$target")
    target_canon=$(readlink -f "$target")
    file_canon=$(readlink -f "$file")
    [ "$target_canon" = "$file_canon" ] && continue
    mkdir -pv "$target_dir"
    ln -sbv "$file_canon" "$target"
  fi
done

# OTHER SOFTWARE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

install chromium
install git
install git-extras
install meld
install tmux
install xclip
install gnome-tweak-tool
install_fedora perl-core

install_ubuntu silversearcher-ag
install_fedora the_silver_searcher

install_fedora neovim python3-neovim python2-neovim

# For compiling YouCompleteMe
install_ubuntu build-essential cmake python-dev python3-dev
install_fedora automake gcc gcc-c++ kernel-devel cmake python-devel python3-devel
